name: Run Sports Prediction
on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta cada medianoche
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Prediction
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python predict.py

      - run: python predict.py
      - name: Commit results
        run: 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update predictions" || exit 0
          git push
