name: Run Sports Prediction

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run Prediction
        env:
          FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        run: python predict.py

      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@://github.com"
          git config --local user.name "github-actions[bot]"
          # Agregamos solo si el archivo existe para evitar el error 'fatal'
          if [ -f "predictions.json" ]; then
            git add predictions.json
            git commit -m "Update predictions: $(date)" || echo "No changes to commit"
            git push
          else
            echo "Error: predictions.json no se encontró."
            exit 1
          fi
